name: Docker Image CI

on:
  push:
    branches: [ master, mmcts/* ]
  pull_request:
    branches: [ master, mmcts/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        registry: docker.pkg.github.com
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}/docker
        tag_with_ref: true
        cache_from: ${{ github.repository }}/docker:latest
